export const REPORTS = [
  { 
    id: 1, title: "Annual Physical Examination", date: "Oct 12, 2024", provider: "Dr. Sarah Johnson", 
    status: "Analyzed", type: "General", cid: "Qm3aR7mZ2jL8oF3nT6sBw4dY1cE5hA0vU9qI7rN2p",
    aiSummary: "Normal physical findings. LDL slightly elevated at 178 mg/dL. Glucose borderline at 108 mg/dL. No acute concerns.",
    conditions: ["Borderline Hyperlipidemia", "Pre-diabetic Glucose"],
    confidence: 91,
  },
  { 
    id: 2, title: "Blood Work – Lipid Panel", date: "Sep 28, 2024", provider: "City Labs Clinic", 
    status: "Analyzed", type: "Laboratory", cid: "Qm7cBk9Xp2mZ4oF1nT8sBw6dY3cE2hA5vU1qI9rN4p",
    aiSummary: "Total cholesterol elevated at 210 mg/dL. HDL within range. Triglycerides borderline. Dietary modification recommended.",
    conditions: ["Hypercholesterolemia (Borderline)"],
    confidence: 88,
  },
  { 
    id: 3, title: "Chest X-Ray Results", date: "Sep 15, 2024", provider: "General Hospital", 
    status: "Processing", type: "Radiology", cid: "Pending...",
    aiSummary: null,
    conditions: [],
    confidence: null,
  },
  { 
    id: 4, title: "Metabolic Screening", date: "Aug 10, 2024", provider: "HealthFirst Labs", 
    status: "Analyzed", type: "Laboratory", cid: "Qm9dE5hA0vU9qI7rN2pX3aR7mZ2jL8oF3nT6sBw4",
    aiSummary: "Thyroid function normal. Kidney and liver panels within expected range. HbA1c at 5.4%, healthy.",
    conditions: [],
    confidence: 95,
  },
  { 
    id: 5, title: "Eye Examination", date: "Jul 22, 2024", provider: "Vision Plus", 
    status: "Analyzed", type: "Optometry", cid: "QmXk9PaR7mZ2jL8oF3nT6sBw4dY1cE5hA0vU9qI7rN",
    aiSummary: "Visual acuity 20/20 both eyes. No signs of diabetic retinopathy or glaucoma.",
    conditions: [],
    confidence: 97,
  },
];

export const PATIENTS = [
  {
    id: "P001",
    displayId: "MED-4F2A-9C1B-E37D",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    summary: "34-year-old male presenting with borderline hyperlipidemia and pre-diabetic glucose levels. No acute symptoms. Recommended lifestyle modifications.",
    conditions: ["Borderline Hyperlipidemia", "Pre-diabetic Glucose"],
    vitals: { bp: "120/78", hr: "72 bpm", temp: "98.4°F", spo2: "98%" },
    lastReport: "Oct 12, 2024",
    reportCount: 12,
    accessStatus: "none",
  },
  {
    id: "P002",
    displayId: "MED-9B7C-3D2E-F5A1",
    age: 52,
    gender: "Female",
    bloodGroup: "A+",
    summary: "52-year-old female with history of hypertension (controlled). Recent ECG shows mild arrhythmia. Currently on antihypertensive medication.",
    conditions: ["Hypertension (Controlled)", "Mild Arrhythmia"],
    vitals: { bp: "138/86", hr: "88 bpm", temp: "98.6°F", spo2: "97%" },
    lastReport: "Oct 05, 2024",
    reportCount: 8,
    accessStatus: "pending",
  },
  {
    id: "P003",
    displayId: "MED-2C8A-6E4F-B1D7",
    age: 28,
    gender: "Male",
    bloodGroup: "B-",
    summary: "28-year-old male with acute respiratory infection. Chest X-ray shows mild consolidation in right lower lobe. Prescribed antibiotics.",
    conditions: ["Acute Respiratory Infection", "Mild Consolidation"],
    vitals: { bp: "115/75", hr: "95 bpm", temp: "101.2°F", spo2: "95%" },
    lastReport: "Sep 28, 2024",
    reportCount: 3,
    accessStatus: "approved",
  },
  {
    id: "P004",
    displayId: "MED-7F1D-4A9C-E2B8",
    age: 67,
    gender: "Female",
    bloodGroup: "AB+",
    summary: "67-year-old female with Type 2 Diabetes (HbA1c: 7.8%). Neuropathy symptoms reported in lower extremities. Eye examination normal.",
    conditions: ["Type 2 Diabetes Mellitus", "Peripheral Neuropathy"],
    vitals: { bp: "128/82", hr: "76 bpm", temp: "98.2°F", spo2: "97%" },
    lastReport: "Sep 15, 2024",
    reportCount: 21,
    accessStatus: "none",
  },
];

export const APPROVED_RECORDS = [
  {
    id: 1,
    title: "Annual Physical Examination",
    date: "Oct 12, 2024",
    type: "General",
    aiSummary: "Patient shows normal cardiovascular function. LDL slightly elevated at 178 mg/dL. Fasting glucose borderline at 108 mg/dL. No acute abnormalities detected.",
    conditions: ["Borderline Hyperlipidemia"],
    keyFindings: ["LDL: 178 mg/dL (Borderline High)", "Fasting Glucose: 108 mg/dL", "BP: 120/78 mmHg (Normal)", "BMI: 24.6 (Healthy)"],
  },
  {
    id: 2,
    title: "Blood Work – Lipid Panel",
    date: "Sep 28, 2024",
    type: "Laboratory",
    aiSummary: "Lipid panel indicates elevated total cholesterol (210 mg/dL). HDL within normal range. Triglycerides borderline at 152 mg/dL. Recommend dietary modifications.",
    conditions: ["Hypercholesterolemia (Borderline)"],
    keyFindings: ["Total Cholesterol: 210 mg/dL", "HDL: 48 mg/dL (Normal)", "LDL: 132 mg/dL", "Triglycerides: 152 mg/dL"],
  },
];
